---

GENESIS_NETWORK_NAME: "Kanda"

PARITY_BIN_LOC: "https://releases.parity.io/ethereum/v2.7.2/x86_64-unknown-linux-gnu/parity"
PARITY_BIN_SHA256: "fe992f0c9b229a4406e82b9ff6d388f4acb4d6ce2782cb79b7bc379e7965ae34"

ORCHESTRATOR_BIN_LOC: ""                                                                                                                
ORCHESTRATOR_BIN_SHA256: ""
 
validator_archive: "off"
bootnode_archive: "off"
moc_archive: "off"
bootnode_orchestrator: "off"

username: "poa"
users:
  - name: "{{ username }}"
home: "/home/{{ username }}"
